### ISSUE TITLE
Email Adressen sammeln und auf github stellen

### ISSUE THREAD

**Issue by alpipego** [wp-berlin/planung#7]
Email Adressen von Orga sammeln und auf github stellen (kein Zwang). 

Verteiler für Ankündigungen, Termine.

**Comment by hofmannsven** [comment]
Sign me up 👍

**Comment by alpipego** [comment]
alpipego@gmail.com

**Comment by berlindave** [comment]
Done: https://github.com/wp-berlin/planung/pull/9

**Comment by alpipego** [comment]
@svenbrier  @tichypress if you want to appear on a potential "Organizers" page on the website, please consent and add your desired email address to this ticket. 

@hofmannsven please also add the email address you want to be listed with.

**Comment by hofmannsven** [comment]
info@hofmannsven.com

**Comment by svenbrier** [comment]
contact@svenbrier.com

**Comment by berlindave** [comment]
Ok … another try: https://github.com/wp-berlin/planung/pull/9

**Comment by alpipego** [comment]
Closed via #9

**Comment by alpipego** [comment]
add André to organizer contacts
